### ISSUE TITLE
Add tooling support to rx-state

### ISSUE THREAD

**Issue by andreElrico** [BioPhoton/rx-angular#109]
One of the "selling points" for ngrx-state over rx-X*-state would be [TOOLING](https://ngrx.io/guide/store-devtools).

So I just wanted to discuss whether its possible to use that redux tooling pipeline with rx-state and whats your opinion on that matter.

+ Is the hustle worth the profit ?

**Comment by BioPhoton** [comment]
I have no clue about the workload but I would appreciate such tooling.

The interesting question would be how to visualize that.

You have any research done so far?

**Comment by Karnaukhov-kh** [comment]
Fireship had a [guide](https://youtu.be/hG7v7quMMwM?t=512 ) on how to create redux pattern with native rxjs [and add redux devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd). Unfortunately video is pretty old and text version of that lesson is removed. Integrating it is a bit tricky because currently library is not require the usage of redux pattern, so there might not be any named actions.

**Comment by andreElrico** [comment]
> I have no clue about the workload but I would appreciate such tooling.
> 
> The interesting question would be how to visualize that.
> 
> You have any research done so far?

Not yet, but I will investigate the provided links. :)

**Comment by BioPhoton** [comment]
I'll close it for now. Feel free to update here or reopen the issue.
