### ISSUE TITLE
@rx-angular/state. Question about optimal usage of select() method.

### ISSUE THREAD

**Issue by Karnaukhov-kh** [BioPhoton/rx-angular#67]
Hi. Awesome library. Started to refactor some views in my project with it and OMG it solves a lot.

As I understand select() method using distinctUntilChanged() under the hood (judging form the stateful.operator.ts). But what about selecting arrays/objects. Should we use our custom distinctUntilChanged() comparison after select?

Let's take a viewModel approach as an example. 

in Component.ts
`model$: Observable<{foo: {prop: 1, arrayProp: [1,2,3,4,5], objProp: {prop: 2, nestedObjProp: {...}}}, bar: 'hello'}> = this.select()`. 

In Component.html
`model$ | async as viewModel` construction somewhere at the root. 

A child component of this view accepts `viewModel.foo` as an input. Each emission of viewModel even if only property `bar` changed will re-render child component because each emitted value has different reference and non-primitive inputs are compared by reference, right? 

What we can do is to make property `foo$ = this.select('foo')`. Pass it directly to child component and use async pipe there. This is promoted in the docs. But each change of `this.$` will trigger new emission of `this.select('foo')` even if `foo` isn't changed. What is an optimal approach here? Go down and select each needed property separately so basically try to stic to obserables of primitives as inputs?

**Comment by hoebbelsB** [comment]
hi @Karnaukhov-kh, thanks for the good question(s). I will try to provide some answers to you :)

> As I understand select() method using distinctUntilChanged() under the hood (judging form the stateful.operator.ts). But what about selecting arrays/objects. Should we use our custom distinctUntilChanged() comparison after select?

Yes, it uses distinctUntilChanged unter the hood, which in case only works correctly for primitive types. For objects, it just checks the reference, since it just does `===` internally. We will come up with an operator for this scenario which gets called `distinctUntilKeysChanged`. For now, if you really need it, you can just apply another `distinctUntilChanged` with a custom comparison function (e.g. lodash's isEqual).

You could use it like this:

```Typescript
import { isEqual } from 'lodash';
readonly foo$ = this.state.select(map({foo}) => ({ foo }), distinctUntilChanged(isEqual));
```

> A child component of this view accepts viewModel.foo as an input. Each emission of viewModel even if only property bar changed will re-render child component because each emitted value has different reference and non-primitive inputs are compared by reference, right?

Yes, if you are using the `async` pipe and bind it to the view like this: `<ng-container *ngIf="model$ | async as model"></ng-container>`, every emission of the `model$` Observable will result in a `markForCheck()` call.

If you bind your `foo$ = this.select('foo')` property as input with the async pipe like this: `<child [input]="foo$ | async"></child>`, every emission of the `foo$` Observable will result in a`markForCheck()` call for the async pipe and for the changed input value. Ultimately this will result in only one re-rendering, since angular internally coalesces those calls.

> What we can do is to make property foo$ = this.select('foo'). Pass it directly to child component and use async pipe there. This is promoted in the docs. But each change of this.$ will trigger new emission of this.select('foo') even if foo isn't changed. What is an optimal approach here?

Yes, this is the most efficient (in terms of renderings) way of handling this scenario. `foo$` should only emit if any of it's properties gets changed or points to a new reference. So if you use `state.set('bar', 'barChanged')`, `foo$` should not emit any change.

Let me know if I could help you or if anything is unclear

**Comment by Karnaukhov-kh** [comment]
Clear as day. Thanks a lot for your answers. 👍
